### ISSUE TITLE
Cleanup/check issues

### ISSUE THREAD

**Issue by psolymos** [analythium/opencpu-1-click#1]
I have successfully used Packer to automate DO 1-click app image build.

**Important note**: I had to add `export DEBIAN_FRONTEND=noninteractive` to the shell block before `apt install` so that postfix installation won't hang waiting for input.

The issues I encountered are the following:

```
digitalocean: Distribution: Ubuntu
    digitalocean: Version: 20.04
    digitalocean:
    digitalocean: [PASS] Supported Operating System Detected: Ubuntu
    digitalocean: [FAIL] Ubuntu 20.04 is not a supported Operating System Version
    digitalocean: [PASS] Cloud-init is installed.
    digitalocean: [PASS] Firewall service (ufw) is active
    digitalocean:
    digitalocean: Updating apt package database to check for security updates, this may take a minute...
    digitalocean:
    digitalocean: [PASS] There are no pending security updates for this image.
    digitalocean:
    digitalocean:
    digitalocean: Checking for log files in /var/log
    digitalocean:
    digitalocean: [WARN] un-cleared log file, /var/log/ufw.log found
    digitalocean:
    digitalocean:
    digitalocean: Checking all user-created accounts...
    digitalocean:
    digitalocean: Checking user: opencpu...
    digitalocean: [PASS] User opencpu has no password set.
    digitalocean: [ OK ] User opencpu does not have an .ssh directory
    digitalocean:
    digitalocean:
    digitalocean: Checking the root account...
    digitalocean: [PASS] User root has no password set.
    digitalocean: [ OK ] User root has no SSH keys present
    digitalocean: [PASS] root's Bash History appears to have been cleared
    digitalocean: [PASS] DigitalOcean Monitoring agent was not found
    digitalocean:
    digitalocean:
    digitalocean: ---------------------------------------------------------------------------------------------------
    digitalocean: Scan Complete.
    digitalocean: One or more tests failed.  Please review these items and re-test.
    digitalocean: ---------------------------------------------------------------------------------------------------
    digitalocean: 7 Tests PASSED
    digitalocean: 1 WARNINGS
    digitalocean: 1 Tests FAILED
    digitalocean: ---------------------------------------------------------------------------------------------------
    digitalocean: Some critical tests failed.  These items must be resolved and this scan re-run before you submit your image to the marketplace.
```

The `[FAIL] Ubuntu 20.04 is not a supported Operating System Version` is strange because I thought 20.04 is a supported base image for marketplace apps (the ShinyProxy 1-click image is based on it).

The `[WARN] un-cleared log file, /var/log/ufw.log found` is also weird because the `90-cleanup.sh` file has this line `rm -rf /var/log/*.gz /var/log/*.[0-9] /var/log/*-???????? /var/log/*.log` which should clear the ufw log among others.

@pachamaltese : any suggestions if these are to be taken seriously, or how to fix? Thanks.
